services:
  helmet_cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: helmet_cpu
    ports:
      - "8000:8000"
    volumes:
      - ./violations:/app/violations
    env_file:
      - .env

  helmet_gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: helmet_gpu
    ports:
      - "8000:8000"
    volumes:
      - ./violations:/app/violations
    env_file:
      - .env
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]